### ISSUE TITLE
Cannot read property 'ember-bootstrap' of undefined

### ISSUE THREAD

**Issue by insightpeter** [ritesh83/ember-cli-wizard#1]
When you install this package via `ember install` and start your server you get this error.

Cannot read property 'ember-bootstrap' of undefined

Found an issue in the ember-bootstrap [here](https://github.com/kaliber5/ember-bootstrap/issues/120).

Any ideas?

**Comment by ritesh83** [comment]
Hi @insightpeter this addon does have a dependency on ember-bootstrap (as mentioned in the Readme). Did you follow the instructions on http://www.ember-bootstrap.com/#/getting-started on how to include or exclude fonts and styles in your app?

Also what version of ember are you using?

**Comment by insightpeter** [comment]
Ember 2.10.
That resolved the issue, thanks.
Peter

**Comment by kliput** [comment]
Hi,
I have the same issue, my configuration in ``ember-cli-build.js`` is as follows:
```javascript
  var app = new EmberApp(defaults, {
    sassOptions: {
      includePaths: [
        'app/styles',
        'app/styles/someicons'
      ]
    },
    'ember-cli-bootstrap-sassy': {
      'js': [
        'tooltip',
        'transition',
        'collapse',
        'alert',
        'dropdown'
      ],
      'glyphicons': false
    },
    'ember-bootstrap': {
      'importBootstrapCSS': false,
      'importBootstrapTheme': false,
      'importBootstrapFont': false
    }
  });
```

The ``ember-bootstrap`` entry is definitely present. I'm Using Ember 2.11 and ember-bootstrap ``1.0.0-alpha.4``. I've tried changing ember-bootstrap version in ember-cli-wizard package.json, but it didn't help.

The ``ember-cli-bootstrap-sassy`` is there because I use some original Bootstrap JS.

How should I configure the ember-bootstrap?

Best regards,
Jakub

**Comment by GottfridL** [comment]
I get the same problem using ember-cli 2.9. I have defined ember-bootstrap in the app options.
Will this problem be solved?

**Comment by ritesh83** [comment]
Released a new version that does not bring in ember-bootstrap as a dependency on ember install. This addon still needs bootstrap for styling but one should install it separately.
